version: '3.8'

services:
  # Django service with Daphne
  web:
    build: .
    container_name: tobaco_curring_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 curing_backend.asgi:application"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mqtt
    environment:
      - DJANGO_SETTINGS_MODULE=curing_backend.settings
      - REDIS_URL=redis://redis:6379/0
    networks:
      - mynetwork

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  # MQTT broker service
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-log: